# Generated by Django 4.1.7 on 2023-04-12 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hotel',
            name='image',
            field=models.FileField(upload_to='img/'),
        ),
    ]
